version: '3.8'

services:
  rf-backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8000:8000
    depends_on:
      - test-db
    networks:
      app_network:
        ipv4_address: 172.20.0.5

  rf-frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend/:/home/app/web
    ports:
      - 3000:3000
    networks:
      app_network:
        ipv4_address: 172.20.0.6

  test-db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      app_network:
        ipv4_address: 172.20.0.4

  pg_adm:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5055:80
    networks:
      app_network:
        ipv4_address: 172.20.0.7

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16