version: '3.8'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8000:8000
    depends_on:
      - test-db

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend/:/home/app/web
    ports:
      - 3000:3000

  test-db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pg_adm:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5055:80

volumes:
  postgres_data: