name: (CAREFUL) update prod
on: 
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USERNAME }}
        key: ${{ secrets.PROD_KEY }}
        port: ${{ secrets.PROD_PORT }}
        script_stop: true
        script: |
          chmod +x ~/docker/bin/*.sh
          docker/bin/stop-containers.sh
          docker/bin/pull.sh
          docker/bin/build-react.sh
          docker/bin/build-and-up-containers.sh
          docker/bin/migrations-django.sh
          docker/bin/collect-static-backend.sh
