name: (CAREFUL) update prod
on: 
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USERNAME }}
        key: ${{ secrets.PROD_KEY }}
        port: ${{ secrets.PROD_PORT }}
        script_stop: true
        script: |
          chmod +x ~/reagent-flow/*.sh
          reagent-flow/stop-containers.sh
          reagent-flow/pull.sh
          reagent-flow/build-react.sh
          reagent-flow/build-and-up-containers.sh
          reagent-flow/migrations-django.sh
          reagent-flow/collect-static-backend.sh
